name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [debug, release]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up CUDA
      uses: actions-hub/cuda@v1.0.0
      with:
        cuda: '11.8'
    
    - name: Set CUDA_HOME
      run: |
        echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make
        
    - name: Build
      run: |
        make BUILD_TYPE=${{ matrix.build-type }}
        
    - name: Run tests (debug only)
      if: matrix.build-type == 'debug'
      run: |
        cd build/debug
        ./tests
        
    - name: Verify benchmark binary (release only)
      if: matrix.build-type == 'release'
      run: |
        cd build/release
        ./benchmarks --version serial 10